<a href="https://colab.research.google.com/github/BJut7021/TH_DeepLearning/blob/main/TH_DL_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor**

In [29]:
import tensorflow as tf
import numpy as np
# tensor 0 chieu
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, dtype=tf.int16)
print(r1)
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)
# tensor 1 chieu
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print('\n',rank_1_tensor)

# tensor 2 chieu
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print('\n',rank_2_tensor)

# tensor n chieu cung voi thuoc tinh
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],
     [5,6,7,8,9]],
    [[10,11,12,13,14],
     [15,16,17,18,19]],
    [[20,21,22,23,24],
     [25,26,27,28,29]]])

print('\n',rank_3_tensor)
print('shape:',rank_3_tensor.shape)
print('type of tensor:',rank_3_tensor.dtype)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)

 tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)

 tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)

 tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


In [30]:
# tao tensor tu dong gan gia tri ban dau
t_zero = tf.zeros([5])
print(t_zero)

t_one = tf.ones([3,3])
print(t_one)

t_2_one = tf.ones([2,2,3])
print(t_2_one)



tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [31]:
# tao tensor tu dong voi gia tri bat ky
t_1 = tf.fill(3,10)
print(t_1)

t_2 = tf.fill([3,3],9)
print('\n',t_2)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)

 tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


In [32]:
# tao tensor 1 chieu voi ham linspace
lin_space = tf.linspace(start=5.0, stop=20.0, num=5)
print(lin_space)


tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


In [33]:
# tao tensor 1 chieu voi ham range
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)



tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [34]:
# tao tensor ngau nhien voi ham random
range_tensor = tf.random.normal([5])
print(range_tensor)

range_tensor = tf.random.normal([3,3])
print('\n',range_tensor)

range_tensor = tf.random.truncated_normal([3,2,3])
print('\n',range_tensor)

range_tensor = tf.random.uniform([3] , minval=0, maxval=10)
print('\n',range_tensor)

range_tensor = tf.random.uniform([3,2,5] , minval=10, maxval=20)
print('\n',range_tensor)
range_tensor = tf.random.shuffle(range_tensor)
print('\n Tensor sau khi xao tron:',tf.random.shuffle(range_tensor))





tf.Tensor([-0.6247754   1.6839125   0.49905795  0.6376776  -1.9326016 ], shape=(5,), dtype=float32)

 tf.Tensor(
[[ 1.4591675  -0.08753531 -1.2211406 ]
 [ 1.1199093  -0.9219297   0.20050478]
 [ 1.3338664   1.7364138  -1.1801864 ]], shape=(3, 3), dtype=float32)

 tf.Tensor(
[[[ 1.1682732  -0.8639899   0.04378436]
  [-0.31137848  0.34568858  0.98120135]]

 [[ 1.02711     1.0783446  -0.26822945]
  [ 0.10233586 -0.7205718  -1.5988748 ]]

 [[-0.55617195 -0.4035413  -1.9521104 ]
  [ 1.6588832   1.1661452   1.6570086 ]]], shape=(3, 2, 3), dtype=float32)

 tf.Tensor([1.6198373 3.3935797 4.888445 ], shape=(3,), dtype=float32)

 tf.Tensor(
[[[16.73964  15.357756 12.469258 16.34724  11.330929]
  [12.327312 11.261767 17.034483 17.430914 11.856594]]

 [[11.27076  10.238373 13.068258 10.817652 13.385668]
  [13.75731  12.954597 10.196484 18.5667   18.273403]]

 [[15.597786 11.556396 15.729767 18.527498 16.837292]
  [15.015775 16.724073 10.649584 14.099897 13.329723]]], shape=(3, 2, 5), dtype=float32)

***Chuyển đổi dữ liệu***

In [35]:
#3.12 chuyen doi du lieu
t_float = tf.constant (3.9, tf.float32)
print(t_float, '_ _ _',t_float.dtype)
t_int = tf.cast(t_float, tf.int32)
print(t_int,'_ _ _',t_float.dtype)


tf.Tensor(3.9, shape=(), dtype=float32) _ _ _ <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) _ _ _ <dtype: 'float32'>


***Tính căn bậc 2***

In [36]:
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)


***Cộng 2 tensor***

In [37]:
a = tf.constant([[1,2]],tf.int32)
b = tf.constant([[3,4]],tf.int32)
c = tf.add(a,b)
d = a + b
print(c)
print(d)


tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


***Nhân 2 tensor***

In [38]:
a = tf.constant([[1,2]],tf.int32)
b = tf.constant([[3,4]],tf.int32)
c = tf.multiply(a,b)
d = a * b
print(c)
print(d)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


***3.15. Các phép toán trên vector và ma trận***

In [39]:
t1 = tf.constant([4., 3., 2.,])
t2 = tf.constant([3., 2., 1.,])
t3 = tf.constant([[1., 2., 3.], [4., 5., 6.]])

t4 = tf.constant([[7.,8.],[9.,10.],[11.,12.]], dtype=tf.float32)


t_square = tf.constant([[1., 2.], [3., 4.]])

dot_x = tf.tensordot(t1 , t2, 0)
dot_y = tf.tensordot(t1 , t2, 1)
print(t1)
print(t2)
print(t3)
print(t4)
print(t_square)
cross = tf.linalg.cross(t1,t2)
mm = tf.matmul(t3,t4)
d = tf.linalg.det(t_square)
trace = tf.linalg.trace(t_square)
trans = tf.transpose(t3)
eye = tf.eye(5,5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 7.  8.]
 [ 9. 10.]
 [11. 12.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(-2.0, shape=(), dtype=float32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


***3.16. Biến trong tensorflow***

In [40]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5,9])
print(diem)
print('Shape',diem.shape)
print('Dtype',diem.dtype)
print('numpy',diem.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape (2,)
Dtype <dtype: 'int32'>
numpy [5 9]


In [41]:
#Phép gán giá trị cho tensor
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5,9])
print(diem)
diem.assign([10,10])
print(diem)


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>


In [42]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5,9])
print(diem)
diem.assign([8,10])
diem.assign_add([1,1])
print(diem)
diem.assign_sub([5,5])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>


***3.17. Môi trường tính toán Graph trong tensorflow***

In [43]:
def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x
#'a_function_that_uses_a_graph' la 1 ham TensorFlow
a_function_that_uses_a_graph = tf.function(a_regular_function)

# tao vai tensors
x1= tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
# Goi ham
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()
print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]


*3.17.1.Biến một hàm Python thuần túy sang graph*

In [44]:
def inner_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

#
@tf.function
def outer_function(x):
  y = tf.constant([[2.0], [3.0]])
  b = tf.constant(4.0)

  return inner_function(x, y, b)

#
#
rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print(rs)

[[12.]]


***3.18. Modules, Layers và Models***

In [45]:
class Dense(tf.keras.layers.Layer):
  def __init__(self, in_features, out_features , name=None):
    super().__init__(name=name)
    self.w = tf.Variable(
        tf.random.normal([in_features, out_features]), name='w')
    self.b = tf.Variable(tf.zeros([out_features]), name='b')
  def call(self, x):
    y = tf.matmul(x, self.w) + self.b
    return tf.nn.relu(y)

class SequentialModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)

    self.dense_1 = Dense(in_features=3, out_features=3)
    self.dense_2 = Dense(in_features=3, out_features=2)

  def __call__(self, x):
    x = self.dense_1(x)
    return self.dense_2(x)

#
my_model = SequentialModule(name="the_model")

#
print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))


Model results: tf.Tensor([[0.        5.0502405]], shape=(1, 2), dtype=float32)


***3.19. Lưu weight***

In [46]:
#3.19.1. Lưu checkpoint
chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)


'my_checkpoint'

In [47]:
#3.19.2. Phục hồi checkpoint
new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")

print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor([[0.        5.0502405]], shape=(1, 2), dtype=float32)


***Bài tập***

In [48]:
#7. Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối uniform trong phạm vi [0, 2]
tensor_tf = tf.random.uniform(shape=[3, 2], minval=0, maxval=2)

print(" 7. Tensor :")
print(tensor_tf.numpy())

#8. Cho tensor X = [[1, 2], [3, 4], [5, 6]]. Hãy shuffle X theo chiều thứ nhất (sử dụng random_shuffle)
X = tf.constant([[1, 2], [3, 4], [5, 6]])

# Shuffle tensor X theo chiều thứ nhất
X_shuffled = tf.random.shuffle(X)

print("\n 8. Tensor X ban đầu:\n", X.numpy())
print("\nTensor X sau khi shuffle theo chiều thứ nhất:\n", X_shuffled.numpy())

 7. Tensor :
[[0.5759828 0.2555411]
 [1.7069638 1.5191157]
 [1.2326477 1.9694891]]

 8. Tensor X ban đầu:
 [[1 2]
 [3 4]
 [5 6]]

Tensor X sau khi shuffle theo chiều thứ nhất:
 [[1 2]
 [3 4]
 [5 6]]
