<a href="https://colab.research.google.com/github/BJut7021/TH_DeepLearning/blob/main/TH_DL_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd

my_list = [1, 9, 15, 39]
print('python list:',my_list)
my_numpy_array = np.array(my_list)
print('numpy array',my_numpy_array)

a = np.array([1, 9, 15, 39])
print(a)


c = np.array([(1, 2, 3),
 (4, 5, 6)
 ])
print (c)
print (c.shape)
print (c.dtype)

d = np.array([
 [[1., 2., 3.], [4., 5., 6.]],
 [[7., 8., 9.], [10., 11., 12.]]
 ])
print (d)
print (d.shape)

e = np.zeros((2,2))
f = np.ones((3,3))
print('zero matrix:\n' ,e)
print('one matrix:\n' ,f)


g = np.array([
 [[1., 2., 3.], [4., 5., 6.]],])
print (g)
print (g.shape)
f = g.reshape(3,2)
print (f)


h = np.array([
 [[1., 2., 3.], [4., 5., 6.]],
 [[7., 8., 9.], [10., 11., 12.]]
 ])
print(h)
print(h.shape)
k = h.reshape(2,3,2)
print(k)






python list: [1, 9, 15, 39]
numpy array [ 1  9 15 39]
[ 1  9 15 39]
[[1 2 3]
 [4 5 6]]
(2, 3)
int64
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
zero matrix:
 [[0. 0.]
 [0. 0.]]
one matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[1. 2. 3.]
  [4. 5. 6.]]]
(1, 2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
