<a href="https://colab.research.google.com/github/BJut7021/TH_DeepLearning/blob/main/TH_DL_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

TẠO NUMPY ARRAYY

In [ ]:
import numpy as np

#3.1 tạo array 1 chiều
my_list = [1, 9, 15, 39]
print('python list:',my_list)
my_numpy_array = np.array(my_list)
print('numpy array',my_numpy_array)

a = np.array([1, 9, 15, 39])
print(a)


python list: [1, 9, 15, 39]
numpy array [ 1  9 15 39]
[ 1  9 15 39]


In [ ]:
#3.2 tạo array 2 chiều
c = np.array([(1, 2, 3),
 (4, 5, 6)
 ])
print ('\n',c)
print (c.shape)
print (c.dtype)


 [[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
#3.3 tạo array 3 chiều
d = np.array([
 [[1., 2., 3.], [4., 5., 6.]],
 [[7., 8., 9.], [10., 11., 12.]]
 ])
print ('\n',d)
print (d.shape)


 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
#3.4 tạo array với giá trị ban đầu là 0 hoặc 1
e = np.zeros((2,2))
f = np.ones((3,3))
print('\n zero matrix:\n' ,e)
print('one matrix:\n' ,f)


 zero matrix:
 [[0. 0.]
 [0. 0.]]
one matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3.5. Reshape và Flatten ma trận

In [ ]:
# Reshape
g = np.array([
 [[1., 2., 3.], [4., 5., 6.]],])
print ('\n',g)
print (g.shape)
f = g.reshape(3,2)
print (f)

h = np.array([
 [[1., 2., 3.], [4., 5., 6.]],
 [[7., 8., 9.], [10., 11., 12.]]
 ])
print(h)
print(h.shape)
k = h.reshape(2,3,2)
print(k)

# Platten
l = np.array([
 [[1., 2., 3.], [4., 5., 6.]],
 ])
m = l.flatten()
print(m)


 [[[1. 2. 3.]
  [4. 5. 6.]]]
(1, 2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
[1. 2. 3. 4. 5. 6.]


In [ ]:

# 3.6 thêm dòng data với hstack và vstack
n = np.array([1, 2, 3])
o = np.array([4, 5, 6])
p = np.hstack((n, o))
print('\nHorizontal Append\n',p)
q = np.vstack((n, o))
print('Vertical Append\n',q)


Horizontal Append
 [1 2 3 4 5 6]
Vertical Append
 [[1 2 3]
 [4 5 6]]


3.7. Sinh mảng số ngẫu nhiên

In [ ]:
# 3.7.1 sinh mảng số ngẫu nhiên
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n',a)
b = np.random.randint(100, size=(3,4))
print('Random 2-D array\n',b)
c = np.random.randint(100, size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [62 12 14 82  6]
Random 2-D array
 [[ 1 95 12 88]
 [84 27 60 26]
 [67  7 16 65]]
Random 3-D array
 [[[90 54 45]
  [30 76 11]
  [ 0 66 47]
  [57 65 68]]

 [[96 64 13]
  [33 37 83]
  [18  4  9]
  [91 90 66]]

 [[70 35  2]
  [40 45 29]
  [79 29 34]
  [13 39 66]]]


3.7.2 Sinh mảng số thực trong khoảng [0, 1]

In [ ]:
a = np.random.rand(5)
print('Random 1-D array\n',a)
b = np.random.rand(3,4)
print('Random 2-D array\n',b)
c = np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.18683598 0.80463919 0.99019833 0.0606673  0.30389743]
Random 2-D array
 [[0.93642054 0.86649296 0.18910555 0.97873118]
 [0.83263651 0.51954384 0.14436443 0.09090899]
 [0.42277365 0.61031901 0.62921186 0.85764343]]
Random 3-D array
 [[[0.16165067 0.22845722 0.45645438]
  [0.66359636 0.4408315  0.18597735]
  [0.97333425 0.67312595 0.84247488]
  [0.37466501 0.90665178 0.99925457]]

 [[0.4662589  0.14612038 0.26673064]
  [0.05974892 0.31228718 0.84452888]
  [0.12428037 0.23455155 0.12997037]
  [0.87713973 0.40502257 0.42252378]]

 [[0.45175153 0.33696132 0.60221196]
  [0.05364795 0.2687516  0.08175891]
  [0.43747789 0.4026777  0.51467437]
  [0.13178794 0.22393573 0.62271614]]]


3.7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [ ]:
a = np.random.normal(5, 0.5,10)
print(a)

[5.39630671 3.99341507 4.78117296 5.6723686  4.94489919 5.54620082
 5.81495121 4.69834194 4.40162791 5.85712141]


3.7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [ ]:
a = np.random.choice([3, 5, 7, 8])
print(a)

b = np.random.choice([3, 5, 7, 9], size=(3, 5))
print('\n',b)

5

 [[9 9 9 3 7]
 [9 9 3 5 9]
 [7 9 7 7 7]]


3.8. Thay đổi giá trị của ma trận

In [ ]:
A = np.matrix(np.ones((5,5)))
print('The matrix\n',A)
np.array(A)[2]=2
print('Change values of third row with array\n',A)
np.asarray(A)[2]=2
print('Change values of third row with asarray\n',A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3.9. Sinh dãy số theo khoảng cho trước

In [ ]:
#3.9.1. Dùng hàm arange
# tạo 10 số nguyên từ 1 -> (n-1)
a = np.arange(1,10)
print(a)
# tạo 10 số nguyên từ 1 -> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1,10,2)
print(b)


[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
#3.9.2. Dùng hàm linspace
a = np.linspace(1.,5.,num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


3.10. Index và slice

In [ ]:
#slide
a = np.array([(1,2,3),(4,5,6)])
print(a)
print('first row',a[0])
print('second row',a[1])
#indexing
print('first column',a[:,0])
print('second column',a[:,1])
print('first two values of second row',a[1,:2])

[[1 2 3]
 [4 5 6]]
first row [1 2 3]
second row [4 5 6]
first column [1 4]
second column [2 5]
first two values of second row [4 5]


**PANDAS**


In [ ]:
import pandas as pd

# tao pandas series tu list
a = pd.Series([1., 2., 3.])
print(a)
print('First value',a[0])
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value',b['a'])


0    1.0
1    2.0
2    3.0
dtype: float64
First value 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value 1.0


In [ ]:
# tao pandas series tu dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [ ]:
# tao doi tuong dataframe
h = np.array([[1,2],[3,4]])
df_h = pd.DataFrame(h)
print('\nDataFrame:\n',df_h)


DataFrame:
    0  1
0  1  2
1  3  4


In [ ]:
# tao doi tuong dataframe
h = np.array([[1,2],[3,4]])
df_h = pd.DataFrame(h)
print('\nDataFrame:\n',df_h)

numpy_h = np.array(df_h)
print('Numpy array:\n', numpy_h)


DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [ ]:
# tao DataFrame mang 2 chieu co ten cot
dic = {'Name':['Tom', 'Jack', 'Ricky'],'Age':[28,34,42]}
df = pd.DataFrame(dic)
print('\n',df)


     Name  Age
0    Tom   28
1   Jack   34
2  Ricky   42


In [ ]:
#tao mang 20 x 4
r = np.random.randn(20,4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

        so1       so2       so3       so4
0 -0.742239 -1.269707  1.814137 -1.176511
1 -1.872123  1.064962 -0.008671  0.757602
2 -0.254188  1.892997 -0.053669  0.414420
3  0.348364 -1.512760  0.059713 -0.092292
4 -1.618981  0.674403  1.913567  1.361301


7.1. Nối nhiều DataFrame

In [ ]:
df1 = pd.DataFrame({'Name':['John','Smith','Paul'],'Age':[25,30,50]}, index=[0,1,2])
df2 = pd.DataFrame({'Name':['Adam','Smith'],'Age':[26,11]}, index=[3,4])

df_concat = pd.concat([df1,df2])
print('Concate two DataFrame\n',df_concat)
#Xóa những giá trị ở cột Name trùng nhau

print('Drop duplicatevalues in DataFrame\n',df_concat.drop_duplicates('Name'))

#Sắp xếp theo cột

print('Sort values in DataFrame\n',df_concat.sort_values('Age'))
#Đổi tên cột
df_rename = df_concat.rename(columns={'Name':'Surname','Age':'Age_pupil'})
print('Rename colums of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename colums of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


7.2. Đọc dữ liệu từ CSV

In [ ]:
path = '/content/sample_data/california_housing_train.csv'
COLUMNS = ['longitude', 'latitude']
df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS,index_col=False)
print(df_csv.head())
print(df_csv.shape)
df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)

     longitude   latitude
0    longitude   latitude
1  -114.310000  34.190000
2  -114.470000  34.400000
3  -114.560000  33.690000
4  -114.570000  33.640000
(17001, 2)
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  
(170

/tmp/ipykernel_2786/2602361981.py:3: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS,index_col=False)


7.3. Gom nhóm dữ liệu DataFrame

In [ ]:
path = '/content/sample_data/california_housing_train.csv'
df_csv = pd.read_csv(path, skipinitialspace=True,index_col=False)

print(df_csv.head())
print(df_csv.groupby('housing_median_age').mean().head())
print(df_csv.groupby(['housing_median_age'])['total_rooms'].min().head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  
                     longitude   latitude  total_rooms  total_bedrooms  \
housing_median_age                                                       
1.0                -121

2 Bài tập

In [ ]:
#22. Viết chương trình Pandas tạo và hiển thị dữ liệu DataFrame
exam_data = {
    "name": [
        "Anastasia",
        "Dima",
        "Katherine",
        "James",
        "Emily",
        "Michael",
        "Matthew",
        "Laura",
        "Kevin",
        "Jonas",
    ],
    "score": [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    "attempts": [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    "qualify": ["yes", "no", "yes", "no", "no", "yes", "yes", "no", "no", "yes"],
}
labels = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]
df = pd.DataFrame(exam_data, index=labels)
print(df)

#26. Từ bài 22, cho biết số dòng, số cột của DataFrame
# Lấy số dòng và số cột dưới dạng tuple (số dòng, số cột)
print("\nKích thước (dòng, cột) của DataFrame:", df.shape)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Kích thước (dòng, cột) của DataFrame: (10, 4)
